### ISSUE TITLE
No Config button after enabling

### ISSUE THREAD

**Issue by High-Tower80** [cconard96/jamf#113]
No Config button after enabling the plugin. Not sure what I'm missing thanks

**Screenshots**

<img width="336" alt="Screen Shot 2022-07-24 at 11 50 07 PM" src="https://user-images.githubusercontent.com/105761268/180715730-2a783ff1-8e69-4951-8843-5fcb86065ba0.png">

**System Specifications (please complete the following information):**
 - GLPI Server OS: 10.02, using trial hosted option
 - Browser Safari, chrome macOS
 - Plugin version latest

**Comment by cconard96** [comment]
The config is in Setup > General > Jamf plugin tab.
The plugin doesn't specify a "config URL" so there is no config button in the marketplace view or plugin list.
