### ISSUE TITLE
Jamf Import missing field

### ISSUE THREAD

**Issue by bacus99** [cconard96/jamf#115]
With version 3.0.1, when sync

2022-08-12 08:07:12] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: SELECT * FROM `glpi_plugin_jamf_extensionattributes` WHERE `jamf_id` = '54' AND `itemtype` = 'PluginJamfComputer' AND `jamf_type` = 'Computer' LIMIT 1
  Error: Unknown column 'itemtype' in 'where clause'
  Backtrace :
  src/DBmysqlIterator.php:110                        
  src/DBmysql.php:1048                               DBmysqlIterator->execute()
  src/CommonDBTM.php:573                             DBmysql->request()
  marketplace/jamf/inc/computersync.class.php:292    CommonDBTM->find()
  marketplace/jamf/inc/devicesync.class.php:248      PluginJamfComputerSync->syncExtensionAttributes()
  marketplace/jamf/inc/computersync.class.php:663    PluginJamfDeviceSync::sync()
  marketplace/jamf/inc/computersync.class.php:557    PluginJamfComputerSync::import()
  marketplace/jamf/inc/cron.class.php:56             PluginJamfComputerSync::discover()
  src/CronTask.php:1018                              PluginJamfCron::cronImportJamf()
  marketplace/jamf/ajax/cron.php:50                  **CronTask::launch()**

Needed to add a new column in glpi_plugin_jamf_extensionattributes named itemtype varchar 50

**Comment by cconard96** [comment]
I think I caught this issue while reworking the code tests.
It should be fixed by c21c089a250d6dc0757f3c4eef0fb4c46aa1944b
The field that was missing shouldn't be needed, but it was mistakenly put or left in a database query.

**Comment by bacus99** [comment]
Looks good, only itemtype default NULL and it's OK

**Comment by FlorentDerangere** [comment]
> 



> Looks good, only itemtype default NULL and it's OK

Hello what have you do to fix that issue ?

**Comment by bacus99** [comment]
Bonjour Florent,

Vous pouvez changer le script d’installation ou changer la table directement dans MySQL


Je ne me souviens plus des champs par coeur

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
