### ISSUE TITLE
Import bug

### ISSUE THREAD

**Issue by Maxocode** [cconard96/jamf#119]
Hello,

No import since upgrade Jamf Pro 10.44.0-t1676057531
GLPI 10.0.3 (cloud with teclib) 
No error in log, just an empty discovered devices.
Sync is OK for existing.

**Comment by oprideaux** [comment]
Same Issue, Latest issue of Jamf Pro, GLPI Cloud.

Not discovering any devices. no errors

**Comment by Maxocode** [comment]
Hello,
Solved with reinstall
Warning, when you run the discover, the existing devices in GLPI are showing up

**Comment by patryk-wisniewicz-asi** [comment]
Hi,

I also have the same problem. GLPI Cloud  + Jamf Pro 11.0.1-t1698068630. No import & and empty discovering. Any ideas?

**Comment by cconard96** [comment]
I cannot recreate the issue on 3.0.1. Discovering mobile devices and computers works well.
