### ISSUE TITLE
Looking for Contributors

### ISSUE THREAD

**Issue by cconard96** [cconard96/jamf#121]
I am looking for contributors for this plugin.
As I have changed jobs, I no longer have a personal need for this plugin anymore and there is less incentive to maintain it.
I would rather not see this plugin get abandoned though, so I am putting the call out for anyone who is willing to help make contributions to at least keep it compatible with the latest Jamf and GLPI versions. If you are interested, please reply in this issue. I would be glad to point you in the right direction for getting started with the development of this plugin if needed.

**Comment by pauldouane** [comment]
Hello, i'm intressted for the Hello I am interested in the recovery of the plugin
