### ISSUE TITLE
Can't discover devices

### ISSUE THREAD

**Issue by patryk-wisniewicz-asi** [cconard96/jamf#132]
Hi,

I am having trouble discovering devices. After clicking the "discover now" button, it just reloads without any result. I have tried removing and reinstalling the plugin, but it doesn't seem to work. I used the JAMF plugin before, but it has stopped working now (and I thought it related to the version). Although I have some devices in GLPI, I cannot discover and merge them to have up-to-date information. Can you please suggest a solution to this problem?

**System Specifications (please complete the following information):**
 - GLPI Cloud
 - Browser: Chrome/Safari
 - Plugin version: 3.0.2

**Comment by cconard96** [comment]
Hello,

Is there anything being logged in your GLPI server logs (not sure if you can see them on a cloud instance)?
Also, check your Password Policy on your Jamf instance to make sure that "Allow Basic authentication in addition to Bearer Token authentication" is checked. This plugin still uses basic authentication with the Jamf API, although this will finally change in version 3.1.0 of the plugin (not release yet).

You can find the Password Policy in Settings > User accounts and groups > Password Policy (button in top-right of the list).

**Comment by patryk-wisniewicz-asi** [comment]
I asked Teclib for access to logs because I can't find anything in GLPI.

Password Policy looks like the setup is fine:
<img width="545" alt="image" src="https://github.com/cconard96/jamf/assets/150810308/7e8815f0-bb60-4e01-af8b-d5ff2ebbb8bc">

**Comment by cconard96** [comment]
That error should only show up if you click "Import" without selecting any devices, so unfortunately it doesn't seem related to the other issues.

**Comment by cconard96** [comment]
Official ownership of this plugin is being transferred to Teclib' and this plugin will be available through the GLPI-Network subscription going forward. I will still be the main developer for it, but there will be no new community releases after v3.1.1 which was released today (2024-04-15). This transfer was done to ensure the plugin can survive for many more years and get timely updates and new features.
