### ISSUE TITLE
pmv.json is missing

### ISSUE THREAD

**Issue by bacus99** [cconard96/jamf#134]
**Describe the bug**
Error message when installing v 3.1

**To Reproduce**
copy(/usr/share/glpi/marketplace/jamf/pmv.json): failed to open stream: No such file or directory in /usr/share/glpi/marketplace/jamf/inc/migration.class.php at line 597

**Expected behavior**
Seems to miss a file

File is not there in Github download

**Comment by cconard96** [comment]
You'll have to get the updated file manually. The one included is very outdated anyways.
https://gdmf.apple.com/v2/pmv

This release had an alpha version out for a while, but nobody tested it except myself.
I'll try to review this for the next release and include an updated version of the product model version data file.

**Comment by bacus99** [comment]
Will try to find some bug and behavior to help you.  I downloaded the file as .json and moved it in the folder

**Comment by cconard96** [comment]
Default PMV path fixed in #140.
Default PMV updated with the newest data in #139.
