### ISSUE TITLE
Select all button not working

### ISSUE THREAD

**Issue by bacus99** [cconard96/jamf#135]
**Describe the bug**
The select all doesn't works version  3.1

**To Reproduce**
![image](https://github.com/cconard96/jamf/assets/11425241/0cc593f4-d314-4601-99d8-c51d7b23412a)

**Comment by cconard96** [comment]
This version has been de-listed.
You can continue to use it if you wish. I have no plans to re-list the 3.1.0 version.

**Comment by bacus99** [comment]
UUID matching is a big increase for me, thank you

**Comment by cconard96** [comment]
Fixed by #143.
