### ISSUE TITLE
Compatibility with jamf school

### ISSUE THREAD

**Issue by vbarrage** [cconard96/jamf#146]
Hello,
Is the plugin compatible with the Jamf School platform?

**Comment by cconard96** [comment]
No.  My hope was that they would eventually unify their products with the same API, but that hasn't happened. I also do not have access to a Jamf School instance to do any testing. At some point, I may be able to get an instance through the developer program.

Essentially though, supporting Jamf Schools would require an entirely new API connector in the plugin as well as new sync engines to handle transforming the data we can get from the Jamf School API into GLPI assets.

Right now, I'm not looking to add more features to this plugin. The current state of the project is fixing the issues that currently exist, ensuring support for the latest Jamf Pro and GLPI versions, cleaning up the code, and adding more tests. Depending on a few things happening currently, I may start a new phase for this plugin where new features are being added again.

**Comment by vbarrage** [comment]
Thank you for your response and for the existing plugin.
I hope this can be developed for Jamf school one day.
In the meantime, I'll just export the data to CSV and then re-import it using data injection in GLPI.

De : Curtis Conard ***@***.***>
Envoyé : mardi 2 avril 2024 14:58
À : cconard96/jamf ***@***.***>
Cc : BARRAGE Vincent ***@***.***>; Author ***@***.***>
Objet : Re: [cconard96/jamf] Compatibility with jamf school (Issue #146)


No. My hope was that they would eventually unify their products with the same API, but that hasn't happened. I also do not have access to a Jamf School instance to do any testing. At some point, I may be able to get an instance through the developer program.

Essentially though, supporting Jamf Schools would require an entirely new API connector in the plugin as well as new sync engines to handle transforming the data we can get from the Jamf School API into GLPI assets.

Right now, I'm not looking to add more features to this plugin. The current state of the project is fixing the issues that currently exist, ensuring support for the latest Jamf Pro and GLPI versions, cleaning up the code, and adding more tests. Depending on a few things happening currently, I may start a new phase for this plugin where new features are being added again.

**Comment by cconard96** [comment]
Do you currently have a GLPI Network subscription?

**Comment by vbarrage** [comment]
Yes, why ?

De : Curtis Conard ***@***.***>
Envoyé : mardi 2 avril 2024 16:28
À : cconard96/jamf ***@***.***>
Cc : BARRAGE Vincent ***@***.***>; Author ***@***.***>
Objet : Re: [cconard96/jamf] Compatibility with jamf school (Issue #146)


Do you currently have a GLPI Network subscription?

**Comment by vbarrage** [comment]
For my part, I have been using GLPI for almost 10 years and it has been almost 4 years since I upgraded to the GLPI Network Cloud version. I can only encourage its use given all the advantages it brings, and the documentation is much more extensive and structured.
Unfortunately, I have little development skills but I may be able to help you get a test instance for Jamf School if you want to start developing a new connector. Would you like to i'm looking that up ?


De : Curtis Conard ***@***.***>
Envoyé : mardi 2 avril 2024 16:35
À : cconard96/jamf ***@***.***>
Cc : BARRAGE Vincent ***@***.***>; Author ***@***.***>
Objet : Re: [cconard96/jamf] Compatibility with jamf school (Issue #146)


It may become relevant in the future related to this plugin.

However also, irregardless of this plugin's future I may prioritize requests for new features that come from people who pay for a subscription. This is primarily because although I currently maintain this plugin personally, I also am paid to work full time on GLPI itself and therefore subscriptions are what allow me to get paid. Being able to incentivize new subscription sign-ups and provide value for existing ones is a high priority.

**Comment by cconard96** [comment]
> Unfortunately, I have little development skills but I may be able to help you get a test instance for Jamf School if you want to start developing a new connector. Would you like to i'm looking that up?

There is no need. As a member of their Developer Program, I have a representative that I can reach out to to ask about this. They provided me with my Jamf Pro instance, so they may also provide a Jamf School instance. Although, that product isn't specifically mentioned in their Developer Program information.

**Comment by cconard96** [comment]
Official ownership of this plugin is being transferred to Teclib' and this plugin will be available through the GLPI-Network subscription going forward. I will still be the main developer for it, but there will be no new community releases after v3.1.1 which was released today (2024-04-15). This transfer was done to ensure the plugin can survive for many more years and get timely updates and new features.
