### ISSUE TITLE
Jamf School Support

### ISSUE THREAD

**Issue by cconard96** [cconard96/jamf#66]
**Is your feature request related to a problem? Please describe.**
The plugin currently only supports the Pro product and not School because Jamf School doesn't use the same API schema as Pro. It doesn't seem like the newer Jamf Pro API that has been a WIP as a replacement for the Classic API for over 2.5 years (and still doesn't cover the same features) will provide a common ground for interacting with all of their offerings.

**Describe the solution you'd like**
Allow the the GLPI administrator to specify the type of Jamf installation (Pro or School) and, as best as possible, support the same feature set with the different APIs.

**Additional context**
I think these are the latest API docs for Jamf School, but since it is still hosted on Zuludesk's domain and I can't find any developer reference on Jamf's website, I'm not sure.
https://api.zuludesk.com/docs/

**Comment by rbrannath** [comment]
Hi there,
https://api.zuludesk.com/docs/ is still up to date (v. 3.0.0). From my JAMF School instance I get the same site, but on a different url. There is a APIv2 though, but it is still experimental and not complete.

Another thing, which needs to be considered when talking about JAMF School:
There can be multiple schools _**and**_ locations, each with their own API key. It should be possible to add multiple api keys and api urls.

Best regards!
